# Generated by Django 4.0 on 2022-07-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_grade_student_grade'),
        ('Quiz', '0003_remove_answer_user_answer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.student'),
        ),
    ]
