# Generated by Django 4.0 on 2022-07-03 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_answer_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='num1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='num2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='num3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='num4',
            new_name='option4',
        ),
    ]
