# Generated by Django 4.0 on 2022-07-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_rename_num1_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
