# Generated by Django 4.0 on 2022-07-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Grade',
            new_name='grade',
        ),
    ]
